### PR TITLE
rename kur to kur_ara

### PR DESCRIPTION
**Pull request by Shreeshrii**
@stweil Please review.

### CODE REVIEW

**Comment by BisarOmer** [comment]
@Shreeshrii  Kur is correct, does not need change.

**Review by stweil — CHANGES_REQUESTED** [review]
Should this now use `kmr` instead of `kur_ara` to match the `tessdata` changes?

**Comment by stweil** [comment]
@BisarOmer, would `kmr` be fine?

**Comment by Shreeshrii** [comment]
Please see https://en.m.wikipedia.org/wiki/Kurdish_languages

kmr is kurmanji written in Latin script

ckb is Sorani written in Arabic script

Tesseract 3 kur was in Arabic script.

Tesseract 4 kur was in Latin script and was renamed to kmr.

**Comment by BisarOmer** [comment]
@stweil  `kmr` is fine for the Kurmanji dialect which is written in the Latin alphabet and in `tessdata` should remain as `kmr`, but for the Kurdish central which is written in the  Arabic script. `kur` or  `kur_cen` will be fine and so far tesseract is not trained for Kurdish central so not available at `tessdata`.  and also on [langdata](https://github.com/tesseract-ocr/langdata) kurd_ara needs change

**Comment by BisarOmer** [comment]
@stweil  `kmr` is fine for the Kurmanji dialect which is written in the Latin alphabet and in `tessdata` should remain as `kmr`, but for the Kurdish central which is written in the  Arabic script. `kur` or  `kur_cen` will be fine and so far tesseract is not trained for Kurdish central so not available at `tessdata`.  and also on [langdata](https://github.com/tesseract-ocr/langdata) kurd_ara needs change

**Pull request closed without merging**
